Add presentation for the monoid of partial isometries of a cycle graph
libsemigroups/libsemigroups pull request #433
Opened 2022-12-15 14:49 UTC by MTWhyte

This PR adds a presentation for the monoid of partial isometries of a cycle graph, as described in Theorem 2.8 [here](https://arxiv.org/pdf/2205.02196.pdf).

2022-12-15 15:45 UTC, james-d-mitchell commented
@MTWhyte  I think you'll need to mark some of the tests as `no-valgrind` and `no-coverage` and to add some tests for the exceptions.

2022-12-15 15:55 UTC, MTWhyte commented
Will do, for valgrind!

For the coverage, I've got a test for the exceptions on line `383` already (test case `069`). If I look in 'Files changed' on here, it looks like the code coverage is complaining about tens of code blocks that haven't been modified by this PR.

2023-01-12 11:05 UTC, james-d-mitchell commented on docs/source/api/fpsemi-examples.rst
> +:cite:`Fernandes2022aa`; :cite:`Fernandes2022ab`.
```suggestion
:cite:`Fernandes2022aa`; :cite:`Fernandes2022ab`. 
```

2023-01-15 12:26 UTC, james-d-mitchell commented
Thanks for the PR @MTWhyte I think you need to add the `no-valgrind` tag to a bunch of tests though, since there are several that run for 30+ seconds. Thanks!

2023-01-15 12:31 UTC, james-d-mitchell requested changes
I'm happy with this except for the failing val grind ci job that can be fixed by adding the `no-valgrind` tag to the tests that run for more than a couple of seconds.

2023-01-16 12:01 UTC, MTWhyte commented
Thanks @james-d-mitchell, I've added the `no-valgrind` tags now to the appropriate tests (it's perhaps worth noting that I didn't add or modify these tests as part of this PR, but I imagine that's normal enough).

2023-01-16 12:05 UTC, james-d-mitchell commented
Thanks @MTWhyte feel free to ignore the coverage warnings I'm not sure what they're all about.

2023-01-16 18:31 UTC, merged