Word graph hpp
libsemigroups/libsemigroups pull request #596
Opened 2024-09-09 08:01 UTC by james-d-mitchell

2024-09-16 16:40 UTC, james-d-mitchell commented
I have about 5 TODOs left to do and this is finished.

2024-09-17 18:07 UTC, Joseph-Edwards requested changes
Modulo my few brief comments, this looks good to me! I dragged my eyes over the documentation and the implementation in the `*.tpp` file to try and spot any obvious badness, but I haven't given it a thorough read. If there's a particular section that needs a bit more scrutiny I'm happy to have a more detailed look.

2024-09-18 12:15 UTC, james-d-mitchell commented on tests/test-paths.cpp
> +    // TODO add to word_graph helper namespace
I want to keep this TODO, it's not yet done.

2024-09-18 12:18 UTC, james-d-mitchell commented on include/libsemigroups/word-graph.hpp
> +  //! std::initializer_list<std::vector<Node>> const&)
Annoyingly doesn't fit, but oh well

2024-09-18 12:19 UTC, james-d-mitchell commented on include/libsemigroups/word-graph.hpp
> +    //! out-degree of the word graph.
Well spotted.

2024-09-18 12:20 UTC, james-d-mitchell commented on tests/test-sims.cpp
> +          // FIXME the below doesn't seem to work, but JDM expected it to
Yup for later.

2024-09-18 13:21 UTC, merged