Update Ukkonen for v3
libsemigroups/libsemigroups pull request #611
Opened 2024-09-25 20:59 UTC by Joseph-Edwards

This PR updates `ukkonen.hpp` for v3

2024-09-25 20:59 UTC, Joseph-Edwards commented
This is a draft until python bindings are done.

2024-10-19 11:22 UTC, james-d-mitchell requested changes
Looks good apart from the deletion of the lines at the start of the file (which should remain for the attribution if nothing else), and the fact that some python seems to have slipped into the references. I spotted some of these but there might be more, can you please check and fix them all? Thanks!

2024-10-19 11:22 UTC, james-d-mitchell commented on include/libsemigroups/ukkonen.hpp
> +    //! \sa \ref Ukkonen.throw_if_not_unique_letters.
```suggestion
    //! \sa \ref Ukkonen::throw_if_not_unique_letters.
```
Some python slipped back in here

2024-10-19 11:22 UTC, james-d-mitchell commented on include/libsemigroups/ukkonen.hpp
> +    //! \brief \copybrief Ukkonen.add_word_no_checks
More python

2024-10-19 11:22 UTC, james-d-mitchell commented on include/libsemigroups/ukkonen.hpp
> +    //! \sa \ref Ukkonen.throw_if_not_unique_letters.
more python

2024-10-19 11:22 UTC, james-d-mitchell commented on include/libsemigroups/ukkonen.hpp
> -// This file contains an implementation of a generalised suffix tree, adapted
Note sure why these lines are deleted, can you please undelete them?

2024-10-22 15:55 UTC, Joseph-Edwards commented
> Looks good apart from the deletion of the lines at the start of the file (which should remain for the attribution if nothing else), and the fact that some python seems to have slipped into the references. I spotted some of these but there might be more, can you please check and fix them all? Thanks!

All done now. The 'cpplint' job will (hopefully) pass when #615 is merged.

With regard to the deleted comments at the top of the file, I had moved those comments into the doxygen comments a bit further down so it's visible in the doc, but have now added it back as a normal comment at the top just to be doubly safe.

2024-10-23 08:52 UTC, james-d-mitchell commented
Thanks @Joseph-Edwards can you please rebase onto v3, so that the changes you made for cpplint are picked up?

2024-10-23 11:07 UTC, james-d-mitchell commented
Great! Thanks @Joseph-Edwards

2024-10-23 11:08 UTC, james-d-mitchell approved these changes

2024-10-23 11:08 UTC, merged